CREATE DATABASE 'C:\FortesAbastecimento\Data\FortesAbastecimento.fdb'
USER 'sysdba' PASSWORD 'masterkey'
DEFAULT CHARACTER SET UTF8;

CREATE TABLE TANQUES (
    ID_TANQUE       INTEGER NOT NULL,
    DESCRICAO       VARCHAR(50) NOT NULL, -- Ex: "Gasolina Comum", "Oleo Diesel"
    TIPO_COMBUSTIVEL VARCHAR(20) NOT NULL, -- Pode ser útil para filtros futuros
    CONSTRAINT PK_TANQUE PRIMARY KEY (ID_TANQUE)
);

INSERT INTO TANQUES (ID_TANQUE, DESCRICAO, TIPO_COMBUSTIVEL) VALUES (1, 'Gasolina Comum', 'GASOLINA');
INSERT INTO TANQUES (ID_TANQUE, DESCRICAO, TIPO_COMBUSTIVEL) VALUES (2, 'Oleo Diesel', 'DIESEL');

COMMIT;

CREATE TABLE BOMBAS (
    ID_BOMBA        INTEGER NOT NULL,
    ID_TANQUE       INTEGER NOT NULL,
    NUMERO_BOMBA    INTEGER NOT NULL, -- Ex: 1, 2, 3...
    DESCRICAO       VARCHAR(50),
    CONSTRAINT PK_BOMBA PRIMARY KEY (ID_BOMBA),
    CONSTRAINT FK_BOMBA_TANQUE FOREIGN KEY (ID_TANQUE)
        REFERENCES TANQUES (ID_TANQUE)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

INSERT INTO BOMBAS (ID_BOMBA, ID_TANQUE, NUMERO_BOMBA, DESCRICAO) VALUES (1, 1, 1, 'Bomba Gasolina 1');
INSERT INTO BOMBAS (ID_BOMBA, ID_TANQUE, NUMERO_BOMBA, DESCRICAO) VALUES (2, 1, 2, 'Bomba Gasolina 2');
INSERT INTO BOMBAS (ID_BOMBA, ID_TANQUE, NUMERO_BOMBA, DESCRICAO) VALUES (3, 2, 1, 'Bomba Diesel 1');
INSERT INTO BOMBAS (ID_BOMBA, ID_TANQUE, NUMERO_BOMBA, DESCRICAO) VALUES (4, 2, 2, 'Bomba Diesel 2');

COMMIT;

CREATE TABLE ABASTECIMENTOS (
    ID_ABASTECIMENTO  INTEGER NOT NULL,
    ID_BOMBA          INTEGER NOT NULL,
    DATA_HORA         TIMESTAMP NOT NULL, -- Data e hora do abastecimento
    QUANTIDADE_LITROS NUMERIC(10, 3) NOT NULL, -- Precisão para litros
    PRECO_LITRO NUMERIC(10, 3) NOT NULL, --Preço por litro
    VALOR_TOTAL       NUMERIC(12, 2) NOT NULL, -- Valor total do abastecimento
    IMPOSTO           NUMERIC(12, 2) NOT NULL, -- 13% do valor total
    CONSTRAINT PK_ABASTECIMENTO PRIMARY KEY (ID_ABASTECIMENTO),
    CONSTRAINT FK_ABASTECIMENTO_BOMBA FOREIGN KEY (ID_BOMBA)
        REFERENCES BOMBAS (ID_BOMBA)
        ON DELETE CASCADE
        ON UPDATE CASCADE

);

CREATE INDEX IDX_ABASTECIMENTO_DATA ON ABASTECIMENTOS (DATA_HORA);
CREATE INDEX IDX_ABASTECIMENTO_BOMBA ON ABASTECIMENTOS (ID_BOMBA);

CREATE GENERATOR GEN_ABASTECIMENTO_ID;
SET GENERATOR GEN_ABASTECIMENTO_ID TO 0;

SET TERM ^;

CREATE TRIGGER TRG_ABASTECIMENTO_BI FOR ABASTECIMENTOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
   IF (NEW.ID_ABASTECIMENTO IS NULL) THEN
      NEW.ID_ABASTECIMENTO = GEN_ID(GEN_ABASTECIMENTO_ID, 1);
END^

SET TERM ;^